def create_roster(file_name):
    print("-------------------------------------------------------------------------------------------------------------------------")
    print("You are about to create your roster for next week...")
    print("\n")
    print("**Important note**")
    print("\n")
    print("You are required to be available at least 3 days. If you select less than 3 days of work, you will not get rostered.")
    print("If you select 3 or more days, you will get rostered for all of the available days that you have chosen.")
    print("You can only select 1 available shift, shift duration is 5 hours, anything over will get counted to your overtime rate.")
    print("-------------------------------------------------------------------------------------------------------------------------")
    print("Hit enter to start...")
    input()

    print("----------------")
    print("| AVAILABILITY |")
    print("----------------")
    print("Please select your available days:")
    print("[1] Monday 1 May 2023 ")
    print("[2] Tuesday 2 May 2023")
    print("[3] Wednesday 3 May 2023")
    print("[4] Thursday 4 May 2023")
    print("[5] Friday 5 May 2023")
    print("[6] Saturday 6 May 2023")
    print("[7] Sunday 7 May 2023")
    print("[End] Finish")
    input("Enter the index in the [] to select or enter End to finish creating your roster: ")
    print("-------------------------------------------------------------------------------------------------------------------------\n")